include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_key_in_widget_constructors

analyzer:
  errors:
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
    unnecessary_null_comparison: warning 