name: flutter_ryft_payment
description: A Flutter plugin implementing Ryft payment SDKs for both Android and iOS platforms, offering credit card, Google Pay, and Apple Pay integration.
version: 0.1.0
repository: https://github.com/codeforgeXtm/ryft-test
homepage: https://github.com/codeforgeXtm/ryft-test
issue_tracker: https://github.com/codeforgeXtm/ryft-test/issues
documentation: https://github.com/codeforgeXtm/ryft-test/blob/main/README.md

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryft.flutter_ryft_payment
        pluginClass: FlutterRyftPaymentPlugin
      ios:
        pluginClass: FlutterRyftPaymentPlugin 